server:
    port: 8086

spring:
    datasource:
        driver-class-name: org.postgresql.Driver
        url: ${DATASOURCE_URL}
        username: ${DATASOURCE_USER}
        password: ${DATASOURCE_PASS}
    liquibase:
        enabled: true

logging:
    level:
        root: info
    profiles:
        active: prod

yandexprofile:
    login: javaproteams27@yandex.ru
    token: y0_AgAAAABkHWYcAAhcJAAAAADNMMSQdTIhTbQjRfCCNvyw30mWw_U7WIY