server:
    port: 8086

spring:
    profiles:
        active: prod

logging:
    level:
        root: info
    profiles:
        active: prod

yandexprofile:
    login: javaproteams27@yandex.ru
    token: y0_AgAAAABkHWYcAAhcJAAAAADNMMSQdTIhTbQjRfCCNvyw30mWw_U7WIY